POST /api/2.3/tenders/081571a54a2e44c8a69c2be285d1a3f5/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1047
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "123267b1dd9f4115b083fba5120fd443", 
        "value": {
          "amount": 500
        }
      }, 
      {
        "relatedLot": "d9fc90f1a5a3491f8a35052768fae713", 
        "value": {
          "amount": 500
        }, 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/081571a54a2e44c8a69c2be285d1a3f5/bids/e24ed7afa8c744879b5d2adfee5080bd
{
  "access": {
    "token": "d042c1831923492d9536602e47da3fbf"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "123267b1dd9f4115b083fba5120fd443", 
        "date": "2017-09-05T14:33:13.526515+03:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }, 
      {
        "relatedLot": "d9fc90f1a5a3491f8a35052768fae713", 
        "date": "2017-09-05T14:33:13.527074+03:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-09-05T14:33:13.525800+03:00", 
    "id": "e24ed7afa8c744879b5d2adfee5080bd"
  }
}

