GET /api/2.3/tenders/081571a54a2e44c8a69c2be285d1a3f5/bids/f8f46360d94d4af5b11fe7aac6a89e71?acc_token=0e57256529674ee49d97a40ce10a569b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "f8f46360d94d4af5b11fe7aac6a89e71"
  }
}

