PATCH /api/2.3/tenders/081571a54a2e44c8a69c2be285d1a3f5/lots/d9fc90f1a5a3491f8a35052768fae713?acc_token=211db9411ddc42df9006dfb26ba306fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №2", 
    "title": "Лот №2", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-11-11T00:00:00+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 400.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-09-05T14:33:13.106398+03:00", 
    "id": "d9fc90f1a5a3491f8a35052768fae713"
  }
}

