GET /api/2.3/tenders/081571a54a2e44c8a69c2be285d1a3f5?acc_token=211db9411ddc42df9006dfb26ba306fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification", 
    "complaintPeriod": {
      "startDate": "2017-08-06T14:33:13.913531+03:00", 
      "endDate": "2017-09-01T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-08-06T14:33:13.913531+03:00", 
      "clarificationsUntil": "2017-08-31T00:00:00+03:00", 
      "endDate": "2017-08-26T14:33:13.913531+03:00", 
      "invalidationDate": "2017-09-05T14:33:13.632687+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "081571a54a2e44c8a69c2be285d1a3f5", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-09-05T14:33:13.047541+03:00", 
        "id": "123267b1dd9f4115b083fba5120fd443"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-09-05T14:33:14.076875+03:00", 
        "id": "d9fc90f1a5a3491f8a35052768fae713"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2017-09-05T14:33:14.068348+03:00"
    }, 
    "tenderID": "UA-2017-09-05-000001", 
    "dateModified": "2017-09-05T14:33:14.076875+03:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2017-08-06T14:33:13.913531+03:00", 
      "endDate": "2017-09-05T14:33:13.913531+03:00"
    }, 
    "qualifications": [
      {
        "status": "pending", 
        "lotID": "123267b1dd9f4115b083fba5120fd443", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "f8f46360d94d4af5b11fe7aac6a89e71", 
        "date": "2017-09-05T14:33:14.069102+03:00", 
        "id": "22e96a56d910433085c744d595404193"
      }, 
      {
        "status": "pending", 
        "lotID": "123267b1dd9f4115b083fba5120fd443", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "e24ed7afa8c744879b5d2adfee5080bd", 
        "date": "2017-09-05T14:33:14.069408+03:00", 
        "id": "2981f5480cf94e46a80a83d30c390f3e"
      }
    ], 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2017-09-05T14:33:14.076875+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "123267b1dd9f4115b083fba5120fd443", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676015+03:00", 
          "endDate": "2017-10-25T14:32:47.676061+03:00"
        }, 
        "id": "e8886ef77b3c42beb97b8ef2cac182b6", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "d9fc90f1a5a3491f8a35052768fae713", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676091+03:00", 
          "endDate": "2017-10-25T14:32:47.676113+03:00"
        }, 
        "id": "6ac4db4b3ee346dea64daa3506b18935", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "pending", 
        "id": "f8f46360d94d4af5b11fe7aac6a89e71", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "pending", 
        "id": "e24ed7afa8c744879b5d2adfee5080bd", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

