PATCH /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/cancellations/d27ed4146e5448cf8dc10a40612a4cfe?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/5ee0910177c04ee6bc0ff558a440a138?KeyID=685c36f8&Signature=c87wpiUp6adDTug%252Bv76AExJyDw9UGNHniJWcNLM1Q0NZqz417zpGLkVClHSTwGmA38ij9%2Ffct43GDq5vOHriBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:10.947458+03:00", 
        "id": "a77e24c4c2d848f0978eb6145ca7e5a2", 
        "dateModified": "2017-09-05T14:33:10.947501+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/95a71be8c3064c5b98583b11b3091021?KeyID=685c36f8&Signature=JY82K6BOPaE%252BHVLvFZjkLLFLiVeXBgE%2FI7dmp6C%252BMA2%2FZ8%2F6mnXRrgYWuAIpzb9sar81FCrTAIzSprdf8pFoBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:10.947458+03:00", 
        "id": "a77e24c4c2d848f0978eb6145ca7e5a2", 
        "dateModified": "2017-09-05T14:33:11.507790+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2017-09-05T14:33:11.755583+03:00", 
    "cancellationOf": "tender", 
    "id": "d27ed4146e5448cf8dc10a40612a4cfe"
  }
}

