PATCH /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/questions/dc7fd7b95d2b4d9b946e1e2f90dd2b9f?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2017-09-05T14:33:04.086047+03:00", 
    "title": "Калорійність", 
    "date": "2017-09-05T14:33:04.021197+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "dc7fd7b95d2b4d9b946e1e2f90dd2b9f", 
    "questionOf": "tender"
  }
}

