PATCH /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/qualifications/541f1e5a91494fd4a36f012303c1f937?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "64b08293d197488ea869c61e861b7686", 
    "date": "2017-09-05T14:33:06.863663+03:00", 
    "id": "541f1e5a91494fd4a36f012303c1f937"
  }
}

