PATCH /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/qualifications/7019d7a4ba8e448aa28c518256867070?acc_token=133eb9c3e99e4cdd8e5f765a58ba5ebc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "3fbfd60d89c04439a6ca2aa1ec5295c5", 
    "date": "2017-02-24T15:42:02.698886+02:00", 
    "id": "7019d7a4ba8e448aa28c518256867070"
  }
}

