PATCH /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/qualifications/8303bc7447024a78859de65d94831961?acc_token=d4a9844f70954fa7b9ac79f63f0acd66 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "cfa8f9e2901a4258a0d0413f154c1593", 
    "date": "2017-03-20T15:17:53.980666+02:00", 
    "id": "8303bc7447024a78859de65d94831961"
  }
}

