PATCH /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/qualifications/20f22d833a664ff5b09c59a7db657a4a?acc_token=d4a9844f70954fa7b9ac79f63f0acd66 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "221c12fe7bb440a6b23ccc2f3f705323", 
    "date": "2017-03-20T15:17:53.812537+02:00", 
    "id": "20f22d833a664ff5b09c59a7db657a4a"
  }
}

