GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2017-01-14T15:41:38.096518+02:00", 
      "endDate": "2017-02-10T00:00:00+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/67c60125fe6d4e54958d0395a22f5f73", 
    "enquiryPeriod": {
      "startDate": "2017-01-14T15:41:38.096518+02:00", 
      "clarificationsUntil": "2017-02-09T00:00:00+02:00", 
      "endDate": "2017-02-04T15:41:38.096518+02:00", 
      "invalidationDate": "2017-02-24T15:42:01.027135+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "f891de0689684480b6b611de85ba62ce", 
        "date": "2017-02-24T15:42:02.509622+02:00", 
        "id": "e4ff4ec04bed48a88ffa6c99b158bcfb"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "3fbfd60d89c04439a6ca2aa1ec5295c5", 
        "date": "2017-02-24T15:42:02.698886+02:00", 
        "id": "7019d7a4ba8e448aa28c518256867070"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "671472aa879e44189e15b1aee6457d53", 
        "date": "2017-02-24T15:42:02.878774+02:00", 
        "id": "d4fc108fcf5442cd9ddc91da0302e527"
      }
    ], 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-02-24T16:17:38.096518+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-02-24T15:41:58.946041+02:00", 
        "title": "Калорійність", 
        "date": "2017-02-24T15:41:58.851404+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "6ca357cb4e88461bbca35e0082858a50", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "67c60125fe6d4e54958d0395a22f5f73", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/1b9de2bc1c6a4a34b885dc994c6df2ce?download=9ae27ea0ecc14636a12d0df444f7d644", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:58.468163+02:00", 
        "id": "1b9de2bc1c6a4a34b885dc994c6df2ce", 
        "dateModified": "2017-02-24T15:41:58.468196+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/733ecc8a911a485bacb22feaa4b56531?download=62747c1ad4e843099a12d90391fe9d5f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:58.588839+02:00", 
        "id": "733ecc8a911a485bacb22feaa4b56531", 
        "dateModified": "2017-02-24T15:41:58.588879+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/733ecc8a911a485bacb22feaa4b56531?download=91a6e514c2834bf29afb35a32c5aa25c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:58.588839+02:00", 
        "id": "733ecc8a911a485bacb22feaa4b56531", 
        "dateModified": "2017-02-24T15:41:58.730367+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2017-02-14T15:41:38.096518+02:00", 
      "endDate": "2017-02-24T15:41:38.096518+02:00"
    }, 
    "tenderID": "UA-2017-02-24-000001", 
    "dateModified": "2017-02-24T15:42:04.014477+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2017-01-14T15:41:38.096518+02:00", 
      "endDate": "2017-02-14T15:41:38.096518+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2017-02-24T15:41:38.096518+02:00", 
      "shouldStartAfter": "2017-02-25T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2017-02-24T15:42:03.455765+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097474+02:00", 
          "endDate": "2017-04-15T15:41:38.097517+02:00"
        }, 
        "id": "d126c96ecc03468eb2777495085c6245", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097548+02:00", 
          "endDate": "2017-04-15T15:41:38.097579+02:00"
        }, 
        "id": "c962f04b5c0546ee8b6d2c7464dd526f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/documents/3b71f964e7a9400daf8b92252a59e276?download=e3ccba9cf651465c9aa5653a7c1f2bcf", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-02-24T15:41:59.786386+02:00", 
            "id": "3b71f964e7a9400daf8b92252a59e276", 
            "dateModified": "2017-02-24T15:41:59.786419+02:00"
          }, 
          {
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "Proposal_top_secrets.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/documents/79b978d22b914c0a93454cda885145d0?download=a1721891209b4364918df39d9b422b33", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-02-24T15:41:59.921495+02:00", 
            "id": "79b978d22b914c0a93454cda885145d0", 
            "dateModified": "2017-02-24T15:41:59.921539+02:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "id": "f891de0689684480b6b611de85ba62ce", 
        "eligibilityDocuments": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/eligibility_documents/aeed7b17da5848069e507cdb3e16209d?download=848afbb00aa94746872e687b952dd148", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-02-24T15:42:00.529068+02:00", 
            "id": "aeed7b17da5848069e507cdb3e16209d", 
            "dateModified": "2017-02-24T15:42:00.529102+02:00"
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "3fbfd60d89c04439a6ca2aa1ec5295c5", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "selfEligible": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "selfQualified": true, 
        "id": "671472aa879e44189e15b1aee6457d53"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

