GET /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2017-02-07T15:17:31.152100+02:00", 
      "endDate": "2017-03-06T00:00:00+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/7692f1be5b5b409d8900a9791ae5c3ba", 
    "enquiryPeriod": {
      "startDate": "2017-02-07T15:17:31.152100+02:00", 
      "clarificationsUntil": "2017-03-03T15:17:31.152100+02:00", 
      "endDate": "2017-02-28T15:17:31.152100+02:00", 
      "invalidationDate": "2017-03-20T15:17:52.497412+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "221c12fe7bb440a6b23ccc2f3f705323", 
        "date": "2017-03-20T15:17:53.812537+02:00", 
        "id": "20f22d833a664ff5b09c59a7db657a4a"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "cfa8f9e2901a4258a0d0413f154c1593", 
        "date": "2017-03-20T15:17:53.980666+02:00", 
        "id": "8303bc7447024a78859de65d94831961"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "0f4db61ace5149e598a4fba9eb33692a", 
        "date": "2017-03-20T15:17:54.150172+02:00", 
        "id": "ce1034d1382344bdb7de40acbbb3819c"
      }
    ], 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-03-20T15:53:31.152100+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-03-20T15:17:50.570987+02:00", 
        "title": "Калорійність", 
        "date": "2017-03-20T15:17:50.482004+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "713acfe5273f42d5886c7a30666724ea", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "7692f1be5b5b409d8900a9791ae5c3ba", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/documents/311c9e54927f421cb98ea8f250b08feb?download=535de16400494417a6d5c24dc4739b1b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:50.152980+02:00", 
        "id": "311c9e54927f421cb98ea8f250b08feb", 
        "dateModified": "2017-03-20T15:17:50.153013+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/documents/5476bfc563e1497aa5a97d761a9e2edc?download=7db6a68912094bdaae1f0e2acaeb4a4a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:50.260156+02:00", 
        "id": "5476bfc563e1497aa5a97d761a9e2edc", 
        "dateModified": "2017-03-20T15:17:50.260188+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/documents/5476bfc563e1497aa5a97d761a9e2edc?download=5b7935247b414042b2c483e3b01dfcc1", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:50.260156+02:00", 
        "id": "5476bfc563e1497aa5a97d761a9e2edc", 
        "dateModified": "2017-03-20T15:17:50.372745+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2017-03-10T15:17:31.152100+02:00", 
      "endDate": "2017-03-20T15:17:31.152100+02:00"
    }, 
    "tenderID": "UA-2017-03-20-000001", 
    "dateModified": "2017-03-20T15:17:55.273496+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2017-02-07T15:17:31.152100+02:00", 
      "endDate": "2017-03-10T15:17:31.152100+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2017-03-20T15:17:31.152100+02:00", 
      "shouldStartAfter": "2017-03-21T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2017-03-20T15:17:54.771930+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-04-09T15:17:31.153012+02:00", 
          "endDate": "2017-05-09T15:17:31.153060+02:00"
        }, 
        "id": "d0cc6c129dc84c1ba31bd9c7dca0f51f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-04-09T15:17:31.153091+02:00", 
          "endDate": "2017-05-09T15:17:31.153115+02:00"
        }, 
        "id": "093ef652990046a8895b24f5ba12a9a4", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/documents/f23733747dad4a5b850ec192a5b024ba?download=2fd7a93bc03649a5bf4df0f0084290a3", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-03-20T15:17:51.365905+02:00", 
            "id": "f23733747dad4a5b850ec192a5b024ba", 
            "dateModified": "2017-03-20T15:17:51.365938+02:00"
          }, 
          {
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "Proposal_top_secrets.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/documents/f4e5cb394d8540cd8fa38e71062ca967?download=b1bea1ea6630431192ba68102e3cacfc", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-03-20T15:17:51.490384+02:00", 
            "id": "f4e5cb394d8540cd8fa38e71062ca967", 
            "dateModified": "2017-03-20T15:17:51.490419+02:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "id": "221c12fe7bb440a6b23ccc2f3f705323", 
        "eligibilityDocuments": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/eligibility_documents/eedfd45b55f64bc39e3480a0fea49691?download=694ed30f4d9a4cb2b2b2082588f30418", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-03-20T15:17:52.047345+02:00", 
            "id": "eedfd45b55f64bc39e3480a0fea49691", 
            "dateModified": "2017-03-20T15:17:52.047378+02:00"
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "cfa8f9e2901a4258a0d0413f154c1593", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "selfEligible": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "selfQualified": true, 
        "id": "0f4db61ace5149e598a4fba9eb33692a"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

