PATCH /api/2.3/tenders/93ffec78f6444abcb90e75f38d0a5f39/awards/0515be45af36426ebdd4313e98bc8bfc/complaints/f212d659ae7e4bf9a89f0c2a977abbae?acc_token=d0fe4fdd38444eb784bd4fad0fd4bd88 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "invalid", 
    "type": "claim", 
    "title": "Недостатньо інформації", 
    "satisfied": false, 
    "dateAnswered": "2017-09-05T14:32:53.562473+03:00", 
    "dateSubmitted": "2017-09-05T14:32:53.360382+03:00", 
    "complaintID": "UA-2017-09-05-000001.7", 
    "date": "2017-09-05T14:32:53.572126+03:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "f212d659ae7e4bf9a89f0c2a977abbae"
  }
}

