PATCH /api/2.3/tenders/82477461475e4355a9aa1336f1984ba0/awards/552916d90924467eb43b98a17afd84a7/complaints/e9ca75131d32454483dda1c7f072b1e5 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2016-07-25T17:02:03.810365+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/82477461475e4355a9aa1336f1984ba0/awards/552916d90924467eb43b98a17afd84a7/complaints/e9ca75131d32454483dda1c7f072b1e5/documents/18d6d10446f64e1b9aeda32cfb656367?download=c957c021f2d745c88c4c81d4b3b59217", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-25T17:01:58.696151+03:00", 
        "id": "18d6d10446f64e1b9aeda32cfb656367", 
        "dateModified": "2016-07-25T17:01:58.696185+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/82477461475e4355a9aa1336f1984ba0/awards/552916d90924467eb43b98a17afd84a7/complaints/e9ca75131d32454483dda1c7f072b1e5/documents/a84eeede816c4a998ed3be3ee8722c21?download=b347a962f0bb4e2986b50786921b2031", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-25T17:02:03.508643+03:00", 
        "id": "a84eeede816c4a998ed3be3ee8722c21", 
        "dateModified": "2016-07-25T17:02:03.508677+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2016-07-25T17:02:02.378994+03:00", 
    "dateSubmitted": "2016-07-25T17:01:58.896940+03:00", 
    "complaintID": "UA-2016-07-25-000001.1", 
    "date": "2016-07-25T17:02:03.824283+03:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "e9ca75131d32454483dda1c7f072b1e5"
  }
}

