POST /api/2.3/tenders/93ffec78f6444abcb90e75f38d0a5f39/awards/0515be45af36426ebdd4313e98bc8bfc/complaints/8f62d525c67d4d5db6125b80b4e9be08/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0666093786771$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/93ffec78f6444abcb90e75f38d0a5f39/awards/0515be45af36426ebdd4313e98bc8bfc/complaints/8f62d525c67d4d5db6125b80b4e9be08/documents/fb28cf34202542158d63edb74104aea3
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/bdb7e2777c37431181245b150e12491c?KeyID=d0e0fc2c&Signature=YZucngFvTiRyaQqpOPvQE8ivBh5vwUUMWZJfhsoLdLZEjOJ1jtcy%2FG%2FDb%2FsSFT%2F%252Be9P0teTCHzVPXDo9elDVDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-09-05T14:32:55.287606+03:00", 
    "id": "fb28cf34202542158d63edb74104aea3", 
    "dateModified": "2017-09-05T14:32:55.287626+03:00"
  }
}

