GET /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/f6c990da0ec54501b3489b93b4e75045?acc_token=be7436e14f084600b72954830a2fd9cc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/48e5923d917c4ac682dfb2e9b02d9675?KeyID=685c36f8&Signature=8NPoj1d%2F7O0AgTUeNSe7%252BYoKR9els2I6zHofMGbdqFirlmBkwW2zVF%2F8F26KNF0oFlnTefjbTdaiztvu4V6JAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:04.638135+03:00", 
        "id": "8578988e7e77481f91d92e48884295c4", 
        "dateModified": "2017-09-05T14:33:04.638165+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/f6c990da0ec54501b3489b93b4e75045/documents/d1250b90af7a4167bad5dd833339b40c?download=ed1e9fa107d8453c9213b4ea8eeb4211", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:04.710052+03:00", 
        "id": "d1250b90af7a4167bad5dd833339b40c", 
        "dateModified": "2017-09-05T14:33:04.710070+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/b72040dfe0f04b6b8812e30de36e38ea?KeyID=685c36f8&Signature=8Own3YjoyRFkq7gCYffwz%2FeH55HVHi6Y0v1JUrx3rlK9TBzGHm0UHT3glGyh4wzzGXnZmUi2HfEP%2Fpuf1M1aBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:05.150263+03:00", 
        "id": "2c07110dd95d482ea9d903ce48d3c906", 
        "dateModified": "2017-09-05T14:33:05.150301+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f6c990da0ec54501b3489b93b4e75045", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/f6c990da0ec54501b3489b93b4e75045/financial_documents/559d25fb5440453eb5cd7dd14cab85ea?download=40be76804dd5401b976a817bb0790ef9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:04.855188+03:00", 
        "id": "559d25fb5440453eb5cd7dd14cab85ea", 
        "dateModified": "2017-09-05T14:33:04.855207+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/f6c990da0ec54501b3489b93b4e75045/financial_documents/b083e2e3944d4175b21398b04ec7989d?download=88496d5d31cc4cfbb51cedc62f20b0fe", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:04.982321+03:00", 
        "id": "b083e2e3944d4175b21398b04ec7989d", 
        "dateModified": "2017-09-05T14:33:04.982350+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-09-05T14:33:04.499062+03:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/f6c990da0ec54501b3489b93b4e75045/qualification_documents/f9b9b0afe7b94d6d8b1b816f8a1cc3c8?download=ae7e527dc6d5477d85d7be66048a67db", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:05.294571+03:00", 
        "id": "f9b9b0afe7b94d6d8b1b816f8a1cc3c8", 
        "dateModified": "2017-09-05T14:33:05.294603+03:00"
      }
    ], 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/10d15d00e6e345adb1379ae9717ff733?key_for_bid=f6c990da0ec54501b3489b93b4e75045"
  }
}

