GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce?acc_token=bbb74601680f4eabad882e666d25bf1b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/documents/3b71f964e7a9400daf8b92252a59e276?download=e3ccba9cf651465c9aa5653a7c1f2bcf", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:59.786386+02:00", 
        "id": "3b71f964e7a9400daf8b92252a59e276", 
        "dateModified": "2017-02-24T15:41:59.786419+02:00"
      }, 
      {
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "Proposal_top_secrets.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/documents/79b978d22b914c0a93454cda885145d0?download=a1721891209b4364918df39d9b422b33", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:59.921495+02:00", 
        "id": "79b978d22b914c0a93454cda885145d0", 
        "dateModified": "2017-02-24T15:41:59.921539+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/eligibility_documents/aeed7b17da5848069e507cdb3e16209d?download=848afbb00aa94746872e687b952dd148", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:42:00.529068+02:00", 
        "id": "aeed7b17da5848069e507cdb3e16209d", 
        "dateModified": "2017-02-24T15:42:00.529102+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f891de0689684480b6b611de85ba62ce", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/financial_documents/6371a6295b3c4aae9195bcfdbba21ebd?download=b701a02b30d64a26a778e8f4f1c6ebf9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:42:00.198090+02:00", 
        "id": "6371a6295b3c4aae9195bcfdbba21ebd", 
        "dateModified": "2017-02-24T15:42:00.198141+02:00"
      }, 
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/financial_documents/e921f99566fe4bac802efbcfc9fb331f?download=369cd15313a5437582366dd8c874aee5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:42:00.341968+02:00", 
        "id": "e921f99566fe4bac802efbcfc9fb331f", 
        "dateModified": "2017-02-24T15:42:00.342002+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-02-24T15:41:59.551460+02:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/qualification_documents/f2883a59d1524c9584a90087df05f3ea?download=96e87f449bb546bf9474377abf8cd717", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:42:00.698254+02:00", 
        "id": "f2883a59d1524c9584a90087df05f3ea", 
        "dateModified": "2017-02-24T15:42:00.698292+02:00"
      }
    ]
  }
}

