GET /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323?acc_token=79d89544e581425793805525a089a28c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/documents/f23733747dad4a5b850ec192a5b024ba?download=2fd7a93bc03649a5bf4df0f0084290a3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:51.365905+02:00", 
        "id": "f23733747dad4a5b850ec192a5b024ba", 
        "dateModified": "2017-03-20T15:17:51.365938+02:00"
      }, 
      {
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "Proposal_top_secrets.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/documents/f4e5cb394d8540cd8fa38e71062ca967?download=b1bea1ea6630431192ba68102e3cacfc", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:51.490384+02:00", 
        "id": "f4e5cb394d8540cd8fa38e71062ca967", 
        "dateModified": "2017-03-20T15:17:51.490419+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/eligibility_documents/eedfd45b55f64bc39e3480a0fea49691?download=694ed30f4d9a4cb2b2b2082588f30418", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:52.047345+02:00", 
        "id": "eedfd45b55f64bc39e3480a0fea49691", 
        "dateModified": "2017-03-20T15:17:52.047378+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "221c12fe7bb440a6b23ccc2f3f705323", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/financial_documents/43d9eaf29b394b6398de5b0e6d1ea0cc?download=07395958474647f8958854fdc463a079", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:51.734493+02:00", 
        "id": "43d9eaf29b394b6398de5b0e6d1ea0cc", 
        "dateModified": "2017-03-20T15:17:51.734526+02:00"
      }, 
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/financial_documents/cfa41f3b407a478286d7228b8da4e064?download=3bca9b9e4d304e03b5663f0ee20eafbe", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:51.872561+02:00", 
        "id": "cfa41f3b407a478286d7228b8da4e064", 
        "dateModified": "2017-03-20T15:17:51.872594+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-03-20T15:17:51.138763+02:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/qualification_documents/f22b536203134ca7a0c6a0182bfefb54?download=a68b0907d1b94f10a4c547b449a1911a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:52.192070+02:00", 
        "id": "f22b536203134ca7a0c6a0182bfefb54", 
        "dateModified": "2017-03-20T15:17:52.192109+02:00"
      }
    ], 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/7692f1be5b5b409d8900a9791ae5c3ba?key_for_bid=221c12fe7bb440a6b23ccc2f3f705323"
  }
}

