GET /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/cfa8f9e2901a4258a0d0413f154c1593?acc_token=bb997d2581134933a3498db5c674e900 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-03-20T15:17:52.967908+02:00", 
    "id": "cfa8f9e2901a4258a0d0413f154c1593", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/7692f1be5b5b409d8900a9791ae5c3ba?key_for_bid=cfa8f9e2901a4258a0d0413f154c1593"
  }
}

