GET /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/64b08293d197488ea869c61e861b7686?acc_token=3d340bbfb21142dca103361a8f0e1ca9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-09-05T14:33:05.778517+03:00", 
    "id": "64b08293d197488ea869c61e861b7686", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/10d15d00e6e345adb1379ae9717ff733?key_for_bid=64b08293d197488ea869c61e861b7686"
  }
}

