GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2017-02-24-000001", 
    "tenderPeriod": {
      "startDate": "2017-02-24T15:41:57.901213+02:00", 
      "endDate": "2017-03-27T15:41:38.097607+02:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-05-02T00:00:00+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-02-24T15:41:57.901213+02:00", 
      "endDate": "2017-03-23T00:00:00+03:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2017-02-24T15:41:57.946846+02:00", 
    "dateModified": "2017-02-24T15:41:57.953029+02:00", 
    "procurementMethodType": "aboveThresholdEU", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-24T15:41:57.901213+02:00", 
      "clarificationsUntil": "2017-03-22T15:41:38.097607+02:00", 
      "endDate": "2017-03-17T15:41:38.097607+02:00"
    }, 
    "owner": "broker", 
    "next_check": "2017-03-27T16:41:38.097607+03:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097474+02:00", 
          "endDate": "2017-04-15T15:41:38.097517+02:00"
        }, 
        "id": "d126c96ecc03468eb2777495085c6245", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097548+02:00", 
          "endDate": "2017-04-15T15:41:38.097579+02:00"
        }, 
        "id": "c962f04b5c0546ee8b6d2c7464dd526f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "67c60125fe6d4e54958d0395a22f5f73", 
    "awardCriteria": "lowestCost"
  }
}

