PATCH /api/2.3/tenders/7f214d1710564bec87d585176c176fa8/complaints/7bb0ac1b44514aa0b7b445914acaf9bb?acc_token=97d9ba65ba7447638f2b205f6e04a211 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 250
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Виправлено неконкурентні умови"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "dateAnswered": "2017-09-05T14:32:59.847340+03:00", 
    "dateSubmitted": "2017-09-05T14:32:59.583453+03:00", 
    "complaintID": "UA-2017-09-05-000001.2", 
    "date": "2017-09-05T14:32:59.851336+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "7bb0ac1b44514aa0b7b445914acaf9bb"
  }
}

