PATCH /api/2.3/tenders/7f214d1710564bec87d585176c176fa8/complaints/538150d5623048699790c6c29894fd84?acc_token=9a6fa931021041849fc02170ba5d9eca HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2017-09-05T14:33:01.905241+03:00", 
    "complaintID": "UA-2017-09-05-000001.7", 
    "date": "2017-09-05T14:33:01.914679+03:00", 
    "type": "claim", 
    "id": "538150d5623048699790c6c29894fd84"
  }
}

