GET /api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-07-25T17:02:11.683754+03:00", 
    "tendererActionDate": "2016-07-25T17:02:12.246278+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "d6ed15f4ab5940eba48d7d86c47945c5", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2016-07-25T17:02:09.535802+03:00", 
    "complaintID": "UA-2016-07-25-000001.1", 
    "date": "2016-07-25T17:02:12.254943+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents/2fe3c8a7a8d54d7c925b97695b413cdb?download=bfaf0514296d4113be2973a04de0a45e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-25T17:02:08.793785+03:00", 
        "id": "2fe3c8a7a8d54d7c925b97695b413cdb", 
        "dateModified": "2016-07-25T17:02:08.793825+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents/564456a0a89c4581a24f18cfd9381373?download=953cad52c96447caba6f779c819e5dd4", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-25T17:02:11.496206+03:00", 
        "id": "564456a0a89c4581a24f18cfd9381373", 
        "dateModified": "2016-07-25T17:02:11.496240+03:00"
      }
    ], 
    "dateAccepted": "2016-07-25T17:02:10.803564+03:00"
  }
}

