POST /api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy627496017706$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents/564456a0a89c4581a24f18cfd9381373
{
  "data": {
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents/564456a0a89c4581a24f18cfd9381373?download=953cad52c96447caba6f779c819e5dd4", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-25T17:02:11.496206+03:00", 
    "id": "564456a0a89c4581a24f18cfd9381373", 
    "dateModified": "2016-07-25T17:02:11.496240+03:00"
  }
}

