POST /api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents?acc_token=ec3738ee4195455383d4e7b1e0b0073b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy819372472695$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents/2fe3c8a7a8d54d7c925b97695b413cdb
{
  "data": {
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/cfb65472cffd4d0abf713965373cdbb9/complaints/d6ed15f4ab5940eba48d7d86c47945c5/documents/2fe3c8a7a8d54d7c925b97695b413cdb?download=bfaf0514296d4113be2973a04de0a45e", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-25T17:02:08.793785+03:00", 
    "id": "2fe3c8a7a8d54d7c925b97695b413cdb", 
    "dateModified": "2016-07-25T17:02:08.793825+03:00"
  }
}

