GET /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2017-03-20T15:17:50.570987+02:00", 
      "title": "Калорійність", 
      "date": "2017-03-20T15:17:50.482004+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "713acfe5273f42d5886c7a30666724ea", 
      "questionOf": "tender"
    }
  ]
}

