GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2017-02-24T15:41:58.946041+02:00", 
      "title": "Калорійність", 
      "date": "2017-02-24T15:41:58.851404+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "6ca357cb4e88461bbca35e0082858a50", 
      "questionOf": "tender"
    }
  ]
}

