PATCH /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/documents/79b978d22b914c0a93454cda885145d0?acc_token=bbb74601680f4eabad882e666d25bf1b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "title": "Proposal_top_secrets.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/bids/f891de0689684480b6b611de85ba62ce/documents/79b978d22b914c0a93454cda885145d0?download=a1721891209b4364918df39d9b422b33", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-24T15:41:59.921495+02:00", 
    "id": "79b978d22b914c0a93454cda885145d0", 
    "dateModified": "2017-02-24T15:41:59.921539+02:00"
  }
}

