POST /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/cancellations?acc_token=133eb9c3e99e4cdd8e5f765a58ba5ebc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/cancellations/3803be1303814388b8afa259d427e466
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2017-02-24T15:42:07.349836+02:00", 
    "cancellationOf": "tender", 
    "id": "3803be1303814388b8afa259d427e466"
  }
}

