PATCH /api/2.3/tenders/986e8cf8f5ec47a2bf6253d11404fdc8/qualifications/e2cc18b268714751b01605b902c033f4/complaints/fb9386141a59491e959d38beb0a715e3?acc_token=e8e32d2078e046d39b4f9ac9d4deac5a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "750e933c22ca4bde98521e3f0839ea33", 
    "dateSubmitted": "2017-09-05T14:33:18.321431+03:00", 
    "complaintID": "UA-2017-09-05-000001.8", 
    "date": "2017-09-05T14:33:18.328017+03:00", 
    "type": "claim", 
    "id": "fb9386141a59491e959d38beb0a715e3"
  }
}

