GET /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification", 
    "complaintPeriod": {
      "startDate": "2017-08-05T14:32:47.641594+03:00", 
      "endDate": "2017-09-01T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-08-05T14:32:47.641594+03:00", 
      "clarificationsUntil": "2017-08-31T00:00:00+03:00", 
      "endDate": "2017-08-26T14:32:47.641594+03:00", 
      "invalidationDate": "2017-09-05T14:33:05.545498+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "00137226", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Калорійність", 
        "date": "2017-09-05T14:33:04.021197+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "dateAnswered": "2017-09-05T14:33:04.086047+03:00", 
        "id": "dc7fd7b95d2b4d9b946e1e2f90dd2b9f", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "10d15d00e6e345adb1379ae9717ff733", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/10d146b8cb3d454ba3ce8457b8917f51?KeyID=685c36f8&Signature=9Il0XxoTbfe5gJCZFSNJUcIsWBiOZoLGfWNyqmNnR21FLZyeoE6CG4BR%2F7gl9SJ6F7eZuTowuEjwMVBKpdccDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:03.769721+03:00", 
        "id": "a6e834615790486ebc8d59354abc2d94", 
        "dateModified": "2017-09-05T14:33:03.769753+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/6f12a11c5af74656b5df14fb771acbf9?KeyID=685c36f8&Signature=ilOq8cxH1fnGFUC6fXJVVIK9jg0rRha2MsCa3XaFBzN%252BnIYxPIQRtf0kh2swuUhNOwphzzbhsn0E%2FRm77WI7Dg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:03.846114+03:00", 
        "id": "d12d75b2bf2342beafccdedc93cbdd77", 
        "dateModified": "2017-09-05T14:33:03.846146+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/913aa4a3f5d54b3799cdb1b9175a6657?KeyID=685c36f8&Signature=YXLcSOxy%252BGXafwC10G%2FC5u%2F3e6Z3LDrnZfH9BsozffPBhnt1b5Bpx%2Fj4FyxTLZI%252B3n%2F9oPSvfAYmgOaPupiTCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:03.846114+03:00", 
        "id": "d12d75b2bf2342beafccdedc93cbdd77", 
        "dateModified": "2017-09-05T14:33:03.923981+03:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2017-09-05T14:33:06.399601+03:00"
    }, 
    "tenderID": "UA-2017-09-05-000001", 
    "dateModified": "2017-09-05T14:33:06.413990+03:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2017-08-05T14:32:47.641594+03:00", 
      "endDate": "2017-09-05T14:32:47.641594+03:00"
    }, 
    "qualifications": [
      {
        "status": "pending", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "f6c990da0ec54501b3489b93b4e75045", 
        "date": "2017-09-05T14:33:06.400549+03:00", 
        "id": "e3ac2d85dd444a1785cebc69308c828d"
      }, 
      {
        "status": "pending", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "64b08293d197488ea869c61e861b7686", 
        "date": "2017-09-05T14:33:06.400953+03:00", 
        "id": "541f1e5a91494fd4a36f012303c1f937"
      }, 
      {
        "status": "pending", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "dee539a03526464db2ca4f0dd9b334d3", 
        "date": "2017-09-05T14:33:06.401354+03:00", 
        "id": "4190f004913a41fa9dec899942f1c068"
      }
    ], 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2017-09-05T14:33:06.413990+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676015+03:00", 
          "endDate": "2017-10-25T14:32:47.676061+03:00"
        }, 
        "id": "4fc309bd79dc4dd6a110dff07475880e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676091+03:00", 
          "endDate": "2017-10-25T14:32:47.676113+03:00"
        }, 
        "id": "a1daed46308e4b88bd59efbadfd156b2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "pending", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/48e5923d917c4ac682dfb2e9b02d9675?KeyID=685c36f8&Signature=8NPoj1d%2F7O0AgTUeNSe7%252BYoKR9els2I6zHofMGbdqFirlmBkwW2zVF%2F8F26KNF0oFlnTefjbTdaiztvu4V6JAg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-05T14:33:04.638135+03:00", 
            "id": "8578988e7e77481f91d92e48884295c4", 
            "dateModified": "2017-09-05T14:33:04.638165+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/f6c990da0ec54501b3489b93b4e75045/documents/d1250b90af7a4167bad5dd833339b40c?download=ed1e9fa107d8453c9213b4ea8eeb4211", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-05T14:33:04.710052+03:00", 
            "id": "d1250b90af7a4167bad5dd833339b40c", 
            "dateModified": "2017-09-05T14:33:04.710070+03:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "id": "f6c990da0ec54501b3489b93b4e75045", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/b72040dfe0f04b6b8812e30de36e38ea?KeyID=685c36f8&Signature=8Own3YjoyRFkq7gCYffwz%2FeH55HVHi6Y0v1JUrx3rlK9TBzGHm0UHT3glGyh4wzzGXnZmUi2HfEP%2Fpuf1M1aBg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-05T14:33:05.150263+03:00", 
            "id": "2c07110dd95d482ea9d903ce48d3c906", 
            "dateModified": "2017-09-05T14:33:05.150301+03:00"
          }
        ]
      }, 
      {
        "status": "pending", 
        "id": "64b08293d197488ea869c61e861b7686", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "pending", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/65814ba76bb14c3cadd533bb22412a4a?KeyID=685c36f8&Signature=XWfJSf%2FgFouieOULpSYxpP2VvyxIbrPHRLZgitCTiW25vBpQ8zXvP%252BscAzhYqQKpV2g6MZ1QId8Vd6L44HizAg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-05T14:33:05.883459+03:00", 
            "id": "de4f91ea33bd43adbeb1d1905baed000", 
            "dateModified": "2017-09-05T14:33:05.883487+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/dee539a03526464db2ca4f0dd9b334d3/documents/794211883fd54d3ab9f8f4a719bbe40b?download=0b3a7c5a7be548dbb080f40b956b0cf8", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-05T14:33:05.884335+03:00", 
            "id": "794211883fd54d3ab9f8f4a719bbe40b", 
            "dateModified": "2017-09-05T14:33:05.884364+03:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "id": "dee539a03526464db2ca4f0dd9b334d3", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/a01ce5acc4fa4a018ec4af0d58aaaef9?KeyID=685c36f8&Signature=bTjnN%2FXlSzDIBlgVult9WxhfW5X%252BeXzEPbKOJ7D2nXE63dDR0Bfd07JxgJWWqtYxZaYWxfq6GKmK3wOFyGabDA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-05T14:33:05.886142+03:00", 
            "id": "6c5e87157a9543e9b2c12d19e94135a5", 
            "dateModified": "2017-09-05T14:33:05.886171+03:00"
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

