PATCH /api/2.3/tenders/0afd680f6a3f48059f54ae87ce085ab2/qualifications/3872653f315841469b48180bfd78e868/complaints/d2400872ee6245b6b6ed87799a8164a5?acc_token=8aea575aefce4805a2854bd3a682d38e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/0afd680f6a3f48059f54ae87ce085ab2/qualifications/3872653f315841469b48180bfd78e868/complaints/d2400872ee6245b6b6ed87799a8164a5/documents/16656f5929a4499eaab0873865ecdd8f?download=8a42649def914cadb3390a66ff02c26e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-25T17:02:16.175682+03:00", 
        "id": "16656f5929a4499eaab0873865ecdd8f", 
        "dateModified": "2016-07-25T17:02:16.175722+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2016-07-25T17:02:16.339169+03:00", 
    "complaintID": "UA-2016-07-25-000001.1", 
    "date": "2016-07-25T17:02:16.345080+03:00", 
    "type": "complaint", 
    "id": "d2400872ee6245b6b6ed87799a8164a5"
  }
}

