GET /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids?acc_token=d4a9844f70954fa7b9ac79f63f0acd66 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/documents/f23733747dad4a5b850ec192a5b024ba?download=2fd7a93bc03649a5bf4df0f0084290a3", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-03-20T15:17:51.365905+02:00", 
          "id": "f23733747dad4a5b850ec192a5b024ba", 
          "dateModified": "2017-03-20T15:17:51.365938+02:00"
        }, 
        {
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "Proposal_top_secrets.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/documents/f4e5cb394d8540cd8fa38e71062ca967?download=b1bea1ea6630431192ba68102e3cacfc", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-03-20T15:17:51.490384+02:00", 
          "id": "f4e5cb394d8540cd8fa38e71062ca967", 
          "dateModified": "2017-03-20T15:17:51.490419+02:00"
        }
      ], 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "id": "221c12fe7bb440a6b23ccc2f3f705323", 
      "eligibilityDocuments": [
        {
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/bids/221c12fe7bb440a6b23ccc2f3f705323/eligibility_documents/eedfd45b55f64bc39e3480a0fea49691?download=694ed30f4d9a4cb2b2b2082588f30418", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-03-20T15:17:52.047345+02:00", 
          "id": "eedfd45b55f64bc39e3480a0fea49691", 
          "dateModified": "2017-03-20T15:17:52.047378+02:00"
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "cfa8f9e2901a4258a0d0413f154c1593", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "selfEligible": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "selfQualified": true, 
      "id": "0f4db61ace5149e598a4fba9eb33692a"
    }
  ]
}

