POST /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2574
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/65814ba76bb14c3cadd533bb22412a4a?KeyID=685c36f8&Signature=gUyNhvfY8TqYgHSsUQLaARnjJNe48c%2B1%2Byw0mHbiaWXShV9HegekW%2F1ZUkcvNtgS0NiFDAkvhVrOQw5MMr1aAQ%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0b3a7c5a7be548dbb080f40b956b0cf8?KeyID=685c36f8&Signature=pEA1kd%2BT24Izm%2FCkUcezspDrQMnHsCRznktSW3kgOSsYoSGqQloe7gus%2FLITXbDweFTaapkG2aUDO8G6Zo6BCA%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/a01ce5acc4fa4a018ec4af0d58aaaef9?KeyID=685c36f8&Signature=aAOkZFIs0DHw8L46cmaoQ8ixYap%2F4t3aLd3VXWKL24onm5ZoY7rjjeIXoeB3FC%2Bp2Ri%2FyCmWQiwuSradB3rMAw%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "amount": 5
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/e299fa10c69342b5b90ee84c1552fa89?KeyID=685c36f8&Signature=qVik6mZP3SzABu1KDw5SYrtLJsPX6QG6YAvsdejsh7x0KhQ%2FPgC1SyKPXrJasRzLc5VBEAAoqoJoZOCPiH5oAA%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко", 
          "email": "fake@mail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/c758241812714b21b3353cd59b3f4cb8?KeyID=685c36f8&Signature=wzTYZe6BiquS5A5JIopFy5zQM26kI%2F2oN7D8LNfiwhT0HsK1xFITQBxC4g%2ByEpnh591SHNvi6jDZ4s9%2BVYkNCw%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/dee539a03526464db2ca4f0dd9b334d3
{
  "access": {
    "token": "01043245b6cb49d4a09bda8ee9e45d25"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/dee539a03526464db2ca4f0dd9b334d3/documents/de4f91ea33bd43adbeb1d1905baed000?download=65814ba76bb14c3cadd533bb22412a4a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:05.883459+03:00", 
        "id": "de4f91ea33bd43adbeb1d1905baed000", 
        "dateModified": "2017-09-05T14:33:05.883487+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/dee539a03526464db2ca4f0dd9b334d3/documents/794211883fd54d3ab9f8f4a719bbe40b?download=0b3a7c5a7be548dbb080f40b956b0cf8", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:05.884335+03:00", 
        "id": "794211883fd54d3ab9f8f4a719bbe40b", 
        "dateModified": "2017-09-05T14:33:05.884364+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/dee539a03526464db2ca4f0dd9b334d3/eligibility_documents/6c5e87157a9543e9b2c12d19e94135a5?download=a01ce5acc4fa4a018ec4af0d58aaaef9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:05.886142+03:00", 
        "id": "6c5e87157a9543e9b2c12d19e94135a5", 
        "dateModified": "2017-09-05T14:33:05.886171+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "dee539a03526464db2ca4f0dd9b334d3", 
    "value": {
      "currency": "UAH", 
      "amount": 5.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/dee539a03526464db2ca4f0dd9b334d3/financial_documents/41cde84ddcd44e9dbcde35f5fc4565ec?download=e299fa10c69342b5b90ee84c1552fa89", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:05.885246+03:00", 
        "id": "41cde84ddcd44e9dbcde35f5fc4565ec", 
        "dateModified": "2017-09-05T14:33:05.885278+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-09-05T14:33:05.882393+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/bids/dee539a03526464db2ca4f0dd9b334d3/qualification_documents/0e288e0822be4b62af88cb1ba5b45de8?download=c758241812714b21b3353cd59b3f4cb8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:05.887029+03:00", 
        "id": "0e288e0822be4b62af88cb1ba5b45de8", 
        "dateModified": "2017-09-05T14:33:05.887057+03:00"
      }
    ]
  }
}

