PATCH /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/qualifications/d4fc108fcf5442cd9ddc91da0302e527?acc_token=133eb9c3e99e4cdd8e5f765a58ba5ebc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "671472aa879e44189e15b1aee6457d53", 
    "date": "2017-02-24T15:42:02.878774+02:00", 
    "id": "d4fc108fcf5442cd9ddc91da0302e527"
  }
}

