GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/contracts/f429ec027b464d96ba8cec9150eff3ed/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/contracts/f429ec027b464d96ba8cec9150eff3ed/documents/f5a3ea9f3bbd46eb89b17dfa1b526d86?download=423243138bad4961bd8d4a1a10e09ca5", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2017-02-24T15:42:06.323700+02:00", 
      "id": "f5a3ea9f3bbd46eb89b17dfa1b526d86", 
      "dateModified": "2017-02-24T15:42:06.323768+02:00"
    }
  ]
}

