GET /api/2.3/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.3/tenders?offset=2017-09-05T14%3A33%3A03.327441%2B03%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.3/tenders?offset=2017-09-05T14%3A33%3A03.327441%2B03%3A00", 
    "offset": "2017-09-05T14:33:03.327441+03:00"
  }, 
  "data": [
    {
      "id": "10d15d00e6e345adb1379ae9717ff733", 
      "dateModified": "2017-09-05T14:33:03.327441+03:00"
    }
  ]
}

