PATCH /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/contracts/a6af35ebb71f41eabaae61833fe46c17?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 118
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "period": {
      "startDate": "2017-09-05T14:33:09.589395+03:00", 
      "endDate": "2018-09-05T14:33:09.589433+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676015+03:00", 
          "endDate": "2017-10-25T14:32:47.676061+03:00"
        }, 
        "id": "4fc309bd79dc4dd6a110dff07475880e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676091+03:00", 
          "endDate": "2017-10-25T14:32:47.676113+03:00"
        }, 
        "id": "a1daed46308e4b88bd59efbadfd156b2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract#1", 
    "period": {
      "startDate": "2017-09-05T14:33:09.589395+03:00", 
      "endDate": "2018-09-05T14:33:09.589433+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-09-05T14:33:09.422409+03:00", 
    "awardID": "0156fb93db344e81b6a0acc36c3e575c", 
    "id": "a6af35ebb71f41eabaae61833fe46c17", 
    "contractID": "UA-2017-09-05-000001-1"
  }
}

