GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/contracts/f429ec027b464d96ba8cec9150eff3ed?acc_token=133eb9c3e99e4cdd8e5f765a58ba5ebc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "language": "uk", 
        "title": "contract_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/contracts/f429ec027b464d96ba8cec9150eff3ed/documents/f5a3ea9f3bbd46eb89b17dfa1b526d86?download=423243138bad4961bd8d4a1a10e09ca5", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:42:06.323700+02:00", 
        "id": "f5a3ea9f3bbd46eb89b17dfa1b526d86", 
        "dateModified": "2017-02-24T15:42:06.323768+02:00"
      }, 
      {
        "language": "en", 
        "title": "contract_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/contracts/f429ec027b464d96ba8cec9150eff3ed/documents/97925f157e454a93ab0360663e1074ed?download=88c37354c0924dbfadeb475d4e4fc139", 
        "format": "application/msword", 
        "title_en": "Title of Document", 
        "description_en": "Description of Document", 
        "datePublished": "2017-02-24T15:42:06.685539+02:00", 
        "documentOf": "tender", 
        "id": "97925f157e454a93ab0360663e1074ed", 
        "dateModified": "2017-02-24T15:42:06.685598+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097474+02:00", 
          "endDate": "2017-04-15T15:41:38.097517+02:00"
        }, 
        "id": "d126c96ecc03468eb2777495085c6245", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097548+02:00", 
          "endDate": "2017-04-15T15:41:38.097579+02:00"
        }, 
        "id": "c962f04b5c0546ee8b6d2c7464dd526f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract#1", 
    "period": {
      "startDate": "2017-02-24T15:42:05.754728+02:00", 
      "endDate": "2018-02-24T15:42:05.754784+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-02-24T15:42:05.493979+02:00", 
    "awardID": "78a29a4fe47842b5be748917c31795bf", 
    "id": "f429ec027b464d96ba8cec9150eff3ed", 
    "contractID": "UA-2017-02-24-000001-1"
  }
}

