GET /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/contracts/72fecb21dc614b408d3b1a42431a94d1/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/contracts/72fecb21dc614b408d3b1a42431a94d1/documents/02377329da834430940ecd4b88f23954?download=eb96f3a160364f8f9cce3687bddf0ced", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2017-03-20T15:17:57.455003+02:00", 
      "id": "02377329da834430940ecd4b88f23954", 
      "dateModified": "2017-03-20T15:17:57.455069+02:00"
    }
  ]
}

