GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/1b9de2bc1c6a4a34b885dc994c6df2ce?acc_token=133eb9c3e99e4cdd8e5f765a58ba5ebc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/1b9de2bc1c6a4a34b885dc994c6df2ce?download=9ae27ea0ecc14636a12d0df444f7d644", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-24T15:41:58.468163+02:00", 
    "previousVersions": [], 
    "id": "1b9de2bc1c6a4a34b885dc994c6df2ce", 
    "dateModified": "2017-02-24T15:41:58.468196+02:00"
  }
}

