PATCH /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/cancellations/d27ed4146e5448cf8dc10a40612a4cfe?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2017-09-05T14:33:10.763187+03:00", 
    "cancellationOf": "tender", 
    "id": "d27ed4146e5448cf8dc10a40612a4cfe"
  }
}

