PATCH /api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba?acc_token=d4a9844f70954fa7b9ac79f63f0acd66 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-03-28T15:17:50.896634+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2017-02-20T15:17:50.683092+02:00", 
      "endDate": "2017-03-24T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-20T15:17:50.683092+02:00", 
      "clarificationsUntil": "2017-03-23T00:00:00+02:00", 
      "endDate": "2017-03-18T15:17:50.896634+02:00", 
      "invalidationDate": "2017-03-20T15:17:51.031853+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-03-28T16:17:50.896634+03:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-03-20T15:17:50.570987+02:00", 
        "title": "Калорійність", 
        "date": "2017-03-20T15:17:50.482004+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "713acfe5273f42d5886c7a30666724ea", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "7692f1be5b5b409d8900a9791ae5c3ba", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/documents/311c9e54927f421cb98ea8f250b08feb?download=535de16400494417a6d5c24dc4739b1b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:50.152980+02:00", 
        "id": "311c9e54927f421cb98ea8f250b08feb", 
        "dateModified": "2017-03-20T15:17:50.153013+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/documents/5476bfc563e1497aa5a97d761a9e2edc?download=7db6a68912094bdaae1f0e2acaeb4a4a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:50.260156+02:00", 
        "id": "5476bfc563e1497aa5a97d761a9e2edc", 
        "dateModified": "2017-03-20T15:17:50.260188+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/7692f1be5b5b409d8900a9791ae5c3ba/documents/5476bfc563e1497aa5a97d761a9e2edc?download=5b7935247b414042b2c483e3b01dfcc1", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-20T15:17:50.260156+02:00", 
        "id": "5476bfc563e1497aa5a97d761a9e2edc", 
        "dateModified": "2017-03-20T15:17:50.372745+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2017-03-20-000001", 
    "dateModified": "2017-03-20T15:17:51.036750+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-02-20T15:17:50.683092+02:00", 
      "endDate": "2017-03-28T15:17:50.896634+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-05-03T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2017-03-20T15:17:49.648969+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-04-09T15:17:31.153012+02:00", 
          "endDate": "2017-05-09T15:17:31.153060+02:00"
        }, 
        "id": "d0cc6c129dc84c1ba31bd9c7dca0f51f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-04-09T15:17:31.153091+02:00", 
          "endDate": "2017-05-09T15:17:31.153115+02:00"
        }, 
        "id": "093ef652990046a8895b24f5ba12a9a4", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

