GET /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2017-08-08T14:33:04.175693+03:00", 
      "endDate": "2017-09-03T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-08-08T14:33:04.175693+03:00", 
      "clarificationsUntil": "2017-08-31T14:33:04.175693+03:00", 
      "endDate": "2017-08-28T14:33:04.175693+03:00", 
      "invalidationDate": "2017-09-05T14:33:03.924532+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-09-07T14:33:04.175693+03:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-09-05T14:33:04.086047+03:00", 
        "title": "Калорійність", 
        "date": "2017-09-05T14:33:04.021197+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "dc7fd7b95d2b4d9b946e1e2f90dd2b9f", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "10d15d00e6e345adb1379ae9717ff733", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/10d146b8cb3d454ba3ce8457b8917f51?KeyID=685c36f8&Signature=9Il0XxoTbfe5gJCZFSNJUcIsWBiOZoLGfWNyqmNnR21FLZyeoE6CG4BR%2F7gl9SJ6F7eZuTowuEjwMVBKpdccDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:03.769721+03:00", 
        "id": "a6e834615790486ebc8d59354abc2d94", 
        "dateModified": "2017-09-05T14:33:03.769753+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/6f12a11c5af74656b5df14fb771acbf9?KeyID=685c36f8&Signature=ilOq8cxH1fnGFUC6fXJVVIK9jg0rRha2MsCa3XaFBzN%252BnIYxPIQRtf0kh2swuUhNOwphzzbhsn0E%2FRm77WI7Dg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:03.846114+03:00", 
        "id": "d12d75b2bf2342beafccdedc93cbdd77", 
        "dateModified": "2017-09-05T14:33:03.846146+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/913aa4a3f5d54b3799cdb1b9175a6657?KeyID=685c36f8&Signature=YXLcSOxy%252BGXafwC10G%2FC5u%2F3e6Z3LDrnZfH9BsozffPBhnt1b5Bpx%2Fj4FyxTLZI%252B3n%2F9oPSvfAYmgOaPupiTCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:33:03.846114+03:00", 
        "id": "d12d75b2bf2342beafccdedc93cbdd77", 
        "dateModified": "2017-09-05T14:33:03.923981+03:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2017-09-05-000001", 
    "dateModified": "2017-09-05T14:33:04.093193+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-08-08T14:33:04.175693+03:00", 
      "endDate": "2017-09-07T14:33:04.175693+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-10-13T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2017-09-05T14:33:03.322866+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676015+03:00", 
          "endDate": "2017-10-25T14:32:47.676061+03:00"
        }, 
        "id": "4fc309bd79dc4dd6a110dff07475880e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-09-25T14:32:47.676091+03:00", 
          "endDate": "2017-10-25T14:32:47.676113+03:00"
        }, 
        "id": "a1daed46308e4b88bd59efbadfd156b2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

PATCH /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

