GET /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73?acc_token=133eb9c3e99e4cdd8e5f765a58ba5ebc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2017-01-27T15:41:59.059296+02:00", 
      "endDate": "2017-02-22T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-01-27T15:41:59.059296+02:00", 
      "clarificationsUntil": "2017-02-21T15:41:59.059296+02:00", 
      "endDate": "2017-02-16T15:41:59.059296+02:00", 
      "invalidationDate": "2017-02-24T15:41:58.730847+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-02-26T15:41:59.059296+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-02-24T15:41:58.946041+02:00", 
        "title": "Калорійність", 
        "date": "2017-02-24T15:41:58.851404+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "6ca357cb4e88461bbca35e0082858a50", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "67c60125fe6d4e54958d0395a22f5f73", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/1b9de2bc1c6a4a34b885dc994c6df2ce?download=9ae27ea0ecc14636a12d0df444f7d644", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:58.468163+02:00", 
        "id": "1b9de2bc1c6a4a34b885dc994c6df2ce", 
        "dateModified": "2017-02-24T15:41:58.468196+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/733ecc8a911a485bacb22feaa4b56531?download=62747c1ad4e843099a12d90391fe9d5f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:58.588839+02:00", 
        "id": "733ecc8a911a485bacb22feaa4b56531", 
        "dateModified": "2017-02-24T15:41:58.588879+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73/documents/733ecc8a911a485bacb22feaa4b56531?download=91a6e514c2834bf29afb35a32c5aa25c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-24T15:41:58.588839+02:00", 
        "id": "733ecc8a911a485bacb22feaa4b56531", 
        "dateModified": "2017-02-24T15:41:58.730367+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2017-02-24-000001", 
    "dateModified": "2017-02-24T15:41:58.954138+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-01-27T15:41:59.059296+02:00", 
      "endDate": "2017-02-26T15:41:59.059296+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-04-03T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2017-02-24T15:41:57.946846+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097474+02:00", 
          "endDate": "2017-04-15T15:41:38.097517+02:00"
        }, 
        "id": "d126c96ecc03468eb2777495085c6245", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-16T15:41:38.097548+02:00", 
          "endDate": "2017-04-15T15:41:38.097579+02:00"
        }, 
        "id": "c962f04b5c0546ee8b6d2c7464dd526f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

PATCH /api/2.3/tenders/67c60125fe6d4e54958d0395a22f5f73?acc_token=133eb9c3e99e4cdd8e5f765a58ba5ebc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

