POST /api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/documents?acc_token=0bee20f4b4c742228cb56ae02d4d38aa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy568461166862$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/10d15d00e6e345adb1379ae9717ff733/documents/d12d75b2bf2342beafccdedc93cbdd77
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/6f12a11c5af74656b5df14fb771acbf9?KeyID=685c36f8&Signature=ilOq8cxH1fnGFUC6fXJVVIK9jg0rRha2MsCa3XaFBzN%252BnIYxPIQRtf0kh2swuUhNOwphzzbhsn0E%2FRm77WI7Dg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-09-05T14:33:03.846114+03:00", 
    "id": "d12d75b2bf2342beafccdedc93cbdd77", 
    "dateModified": "2017-09-05T14:33:03.846146+03:00"
  }
}

